<?php

return [
    'locales' => [
        'it_IT',
        'ar_JO',
        'be_BE',
        'bn_BD',
        'da_DK',
        'de_DE',
        'en_AU',
        'en_GB',
        'en_PH',
        'en_US',
        'es_AR',
        'es_PE',
        'fa_IR',
        'fr_BE',
        'fr_FR',
        'hy_AM',
        'is_IS',
        'ja_JP',
        'kk_KZ',
        'lv_LV',
        'ne_NP',
        'nl_NL',
        'pl_PL',
        'pt_PT',
        'ro_RO',
        'sk_SK',
        'sr_Cyrl_RS',
        'sr_RS',
        'tr_TR',
        'vi_VN',
        'zh_TW',
        'at_AT',
        'bg_BG',
        'cs_CZ',
        'de_AT',
        'el_GR',
        'en_CA',
        'en_NZ',
        'en_UG',
        'en_ZA',
        'es_ES',
        'es_VE',
        'fi_FI',
        'fr_CA',
        'hu_HU',
        'id_ID',
        'ka_GE',
        'ko_KR',
        'me_ME',
        'nl_BE',
        'no_NO',
        'pt_BR',
        'ro_MD',
        'ru_RU',
        'sl_SI',
        'sr_Latn_RS',
        'sv_SE',
        'uk_UA',
        'zh_CN'
    ],
    'localesSmall' => [
        'it_IT',
        'en_US',
        'en_GB',
        'fr_FR',
        'da_DK',
        'de_DE',
        'sk_SK',
        'hu_HU',
        'ro_MD',
        'tr_TR'
    ],
    'rosters' => [
        'min' => 11,
        'max' => 18
    ],
];


